on:
  push:
    tags:
      - '*'

name: Release fluent-bit-cli (new tag)
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test and Build
        run: make all
  release-snap:
    name: Release stable snaps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Replace snapcraft version/grade
        run: |
          sed -i -e "s/\$VERSION/${{ steps.get_version.outputs.VERSION }}/g" snap/snapcraft.yaml
          sed -i -e "s/\$GRADE/stable/g" snap/snapcraft.yaml
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: stable
